name: mlflow-env

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - scipy=1.11.4
  - pip:
      - mlflow==2.19.0
      - dagshub==0.5.1
      - cloudpickle==3.1.0
      - psutil==5.9.0
